# Generated by Django 3.0.4 on 2020-06-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20200626_0636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
