# Generated by Django 3.0.4 on 2020-06-26 09:24

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_gallerypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='gallery_images',
            field=wagtail.core.fields.StreamField([('images', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_caption', wagtail.core.blocks.CharBlock(max_length=200))])))]),
        ),
    ]
