# Generated by Django 3.0.4 on 2020-06-26 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('gallery', '0006_auto_20200626_1024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryPage',
        ),
    ]
