# Generated by Django 3.0.4 on 2020-06-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_galleries_gallerypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypage',
            name='intro',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
