# Generated by Django 3.0.4 on 2020-06-28 13:34

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicespage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='intro_text',
        ),
        migrations.AddField(
            model_name='servicespage',
            name='services_content',
            field=wagtail.core.fields.StreamField([('subheading', wagtail.core.blocks.RichTextBlock(features=['h2'], icon='title')), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['p', 'link', 'bold', 'italic'], icon='pilcrow'))], null=True),
        ),
    ]
