# Generated by Django 3.0.4 on 2020-06-21 12:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200621_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 21, 12, 42, 14, 942318, tzinfo=utc), verbose_name='Post date'),
        ),
    ]
