# Generated by Django 3.0.4 on 2020-06-21 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200621_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Post date'),
        ),
    ]
