# Generated by Django 3.0.4 on 2020-06-22 23:43

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200623_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='blog_content',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock(icon='pilcrow'))], null=True),
        ),
    ]
