# Generated by Django 3.0.4 on 2020-06-21 15:38

from django.db import migrations
import django.utils.timezone
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200621_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('blog_body_block', wagtail.core.blocks.StructBlock([('paragraph', wagtail.core.blocks.RichTextBlock(help_text='Add a paragraph', icon='pilcrow', required=True)), ('embed', wagtail.embeds.blocks.EmbedBlock(help_text='Add media link', icon='media', required=True))]))], default=django.utils.timezone.now),
        ),
    ]
