# Generated by Django 3.0.4 on 2020-06-23 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200623_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='intro',
        ),
    ]
