# Generated by Django 3.0.4 on 2020-06-21 15:51

from django.db import migrations
import django.utils.timezone
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200621_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph_block', wagtail.core.blocks.StructBlock([('paragraph', wagtail.core.blocks.RichTextBlock(help_text='Add a paragraph', required=True))])), ('embed_block', wagtail.core.blocks.StructBlock([('embed', wagtail.embeds.blocks.EmbedBlock(help_text='Add media link', required=True))])), ('quote_block', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.CharBlock(help_text='Add quote', min_length=5, required=True))]))], blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
