# Generated by Django 3.0.4 on 2020-06-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200622_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='heading',
            field=models.CharField(help_text='Heading of the article', max_length=250),
        ),
    ]
