# Generated by Django 3.0.4 on 2020-06-24 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepagecarousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
    ]
