# Generated by Django 3.0.4 on 2020-06-28 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0005_remove_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subheader',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='homepagecarousel',
            name='carousel_header',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
