# Generated by Django 3.0.4 on 2020-06-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='intro',
        ),
    ]
