# Generated by Django 3.0.4 on 2020-06-26 10:50

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('about', '0003_auto_20200626_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='about_content',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock(features=['p', 'link', 'bold', 'italic'], icon='pilcrow'))], null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
    ]
