# Generated by Django 3.0.4 on 2020-06-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20200626_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='intro_text',
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
