# Generated by Django 3.0.4 on 2020-06-26 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('about', '0005_auto_20200626_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='about_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
    ]
