# Generated by Django 3.0.4 on 2020-06-28 10:47

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20200626_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='about_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='intro_text',
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_content',
            field=wagtail.core.fields.StreamField([('subheading', wagtail.core.blocks.RichTextBlock(features=['h2'], icon='title')), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['p', 'link', 'bold', 'italic'], icon='pilcrow'))], null=True),
        ),
    ]
