# Generated by Django 3.0.4 on 2020-06-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='pinterest',
            field=models.URLField(blank=True, help_text='Pinterest URL', null=True),
        ),
    ]
