# Generated by Django 3.0.4 on 2020-06-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_websitelogo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
